//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Film.
        /// </summary>
        public static string AddFilmButton {
            get {
                return ResourceManager.GetString("AddFilmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add section.
        /// </summary>
        public static string BehindTheScenesAddButton {
            get {
                return ResourceManager.GetString("BehindTheScenesAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headline:.
        /// </summary>
        public static string BehindTheScenesHeadlineLabel {
            get {
                return ResourceManager.GetString("BehindTheScenesHeadlineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction Text:.
        /// </summary>
        public static string BehindTheScenesIntroductionTextLabel {
            get {
                return ResourceManager.GetString("BehindTheScenesIntroductionTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body:.
        /// </summary>
        public static string BehindTheScenesSectionLabel {
            get {
                return ResourceManager.GetString("BehindTheScenesSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behind The Scenes.
        /// </summary>
        public static string BehindTheScenesTab {
            get {
                return ResourceManager.GetString("BehindTheScenesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Behind-The-Scenes sections were not setup correctly..
        /// </summary>
        public static string BTSError {
            get {
                return ResourceManager.GetString("BTSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons:.
        /// </summary>
        public static string CreditPersonsLabel {
            get {
                return ResourceManager.GetString("CreditPersonsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a primary credit.
        /// </summary>
        public static string CreditPrimaryCheckbox {
            get {
                return ResourceManager.GetString("CreditPrimaryCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role:.
        /// </summary>
        public static string CreditRoleLabel {
            get {
                return ResourceManager.GetString("CreditRoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Credit.
        /// </summary>
        public static string CreditsAddButton {
            get {
                return ResourceManager.GetString("CreditsAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the provided credits provided are too short..
        /// </summary>
        public static string CreditsError {
            get {
                return ResourceManager.GetString("CreditsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string CreditsTab {
            get {
                return ResourceManager.GetString("CreditsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Film.
        /// </summary>
        public static string DeleteFilmButton {
            get {
                return ResourceManager.GetString("DeleteFilmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this film?.
        /// </summary>
        public static string DeleteFilmConfirmationText {
            get {
                return ResourceManager.GetString("DeleteFilmConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm.
        /// </summary>
        public static string DeleteFilmConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteFilmConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Film.
        /// </summary>
        public static string EditFilmButton {
            get {
                return ResourceManager.GetString("EditFilmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops... Something is wrong.
        /// </summary>
        public static string ErrorMessageBoxTitle {
            get {
                return ResourceManager.GetString("ErrorMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film ID:.
        /// </summary>
        public static string FilmIdLabel {
            get {
                return ResourceManager.GetString("FilmIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film.
        /// </summary>
        public static string FilmTab {
            get {
                return ResourceManager.GetString("FilmTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The film could not be saved. Please check all entries and try again..
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string ImagesTab {
            get {
                return ResourceManager.GetString("ImagesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description information entered is too short..
        /// </summary>
        public static string IncorrectDescriptionError {
            get {
                return ResourceManager.GetString("IncorrectDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided length of the film is not valid..
        /// </summary>
        public static string IncorrectFilmTimeError {
            get {
                return ResourceManager.GetString("IncorrectFilmTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered title is invalid..
        /// </summary>
        public static string IncorrectTitleError {
            get {
                return ResourceManager.GetString("IncorrectTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video link provided for the film is not valid..
        /// </summary>
        public static string IncorrectVideoLinkError {
            get {
                return ResourceManager.GetString("IncorrectVideoLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        public static string LengthLabel {
            get {
                return ResourceManager.GetString("LengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Description:.
        /// </summary>
        public static string LongDescriptionLabel {
            get {
                return ResourceManager.GetString("LongDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not provide any categories for this film..
        /// </summary>
        public static string NoCategoriesError {
            get {
                return ResourceManager.GetString("NoCategoriesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Reach Out content provided is too short..
        /// </summary>
        public static string ReachOutError {
            get {
                return ResourceManager.GetString("ReachOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach Out Content:.
        /// </summary>
        public static string ReachOutLabel {
            get {
                return ResourceManager.GetString("ReachOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach Out.
        /// </summary>
        public static string ReachOutTab {
            get {
                return ResourceManager.GetString("ReachOutTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string RevertButton {
            get {
                return ResourceManager.GetString("RevertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchFieldText {
            get {
                return ResourceManager.GetString("SearchFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description:.
        /// </summary>
        public static string ShortDescriptionLabel {
            get {
                return ResourceManager.GetString("ShortDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Link:.
        /// </summary>
        public static string VideoLinkLabel {
            get {
                return ResourceManager.GetString("VideoLinkLabel", resourceCulture);
            }
        }
    }
}
